### ISSUE TITLE
Update event causes CPU usage to hit 100% and stay there

### ISSUE THREAD

**Issue by LordFarquhar** [DuckBiscuitDevs/Tinker#1]
**Describe the bug**
After an update CEvent, devsapp monitor goes to 100% usage and stays there

**To Reproduce**
1. Run DevsApp
2. Ensure you are using a process monitor (I used pm2)
3. Wait for update event (marked by debug log "update")
4. See usage hit 100%

**Expected behavior**
Usage does not increase so dramatically and the usage returns to previous value after event has been handled

**Comment by Dukemz** [comment]
that's really weird
any idea what's causing this?

**Comment by LordFarquhar** [comment]
I literally have no idea, I do know it comes from the `update` timeouts which in turn call `custom_events/checkAnnouncements.js` and `custom_events/checkEvents.js`
Both those files have loops in them but none of them call back to themselves or the update loop
The loop is not being called constantly as the logs show the correct 60 second timeout
![image](https://user-images.githubusercontent.com/65400619/103421093-8abeca80-4b92-11eb-8c77-379bf8f78980.png)

**Comment by LordFarquhar** [comment]
attempting to remove asynchronicity from the function as it was unnecessary (the procedures returned no data) 
`custom_events/checkAnnouncements.js` and `custom_events/checkEvents.js` still need to be asynchronous functions as they await fetchWebhook but they wont be awaited

**Comment by LordFarquhar** [comment]
> attempting to remove asynchronicity from the function as it was unnecessary (the procedures returned no data)
> `custom_events/checkAnnouncements.js` and `custom_events/checkEvents.js` still need to be asynchronous functions as they await fetchWebhook but they wont be awaited

Yeahhh that didn't make any difference, anybody got any ideas?

**Comment by Dukemz** [comment]
I'll be honest, I got nothing
Maybe try disabling `checkAnnouncements.js` and see if it makes a difference. If not, re-enable it and try the other one

**Comment by Dukemz** [comment]
Issue turned out to be related to a module `node_gameloop` eating up the CPU. The problem has been resolved. I think. Probably.
