### ISSUE TITLE
SQL string escape in any command with direct db access

### ISSUE THREAD

**Issue by LordFarquhar** [DuckBiscuitDevs/Tinker#3]
**Describe the bug**
Any command that allows the user to enter values directly into the DB, e.g. a reason for warn or an announcement message, can escape into the sql command itself

**To Reproduce**
(example command to use)
1. Use `da!announce "title" "any text with apostrophes in them like Mark's bike" 0`
2. Shows unexpected error message
3. (Logs `unexpected token near "s" in sql command` in hidden dev logs) That is the "s" after apostrophe and can allow sql command injection

**Expected behavior**
Special characters get escaped with backslash \ or specially coded so as not to produce the sql string escape

**Comment by Dukemz** [comment]
Injections aren't actually possible here because of better-sqlite3's prepared statements only allowing one command per statement, but an error will still throw. You might want to rename this

**Comment by LordFarquhar** [comment]
Issue has been remedied for any command that

**Comment by Dukemz** [comment]
yeet it done been fixed
